"""empty message

Revision ID: e9de94ab8a1
Revises: None
Create Date: 2016-11-23 21:47:19.920909

"""

# revision identifiers, used by Alembic.
revision = 'e9de94ab8a1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
